### ISSUE TITLE
Expand GPU support with onnx runtime

### ISSUE THREAD

**Issue by Patchethium** [Hiroshiba/voicevox_core#39]
## 内容

So we have an onnx model besides the pytorch one, right? As far as I know this means it can run on onnx runtime (ORT), which supports multiple backends like directML and MIGraphX which supports AMD and even Intel GPUs.

### Pros 良くなる点

GPU acceleration for more users

### Cons 悪くなる点

It needs someone to write the code

### 実現方法

I don't know much about deep learning frameworks, but following the [doc](https://onnxruntime.ai/docs/) of ORT should be a good start.

## その他

Part of the intention of this issue is to ask if the solution is possible, if the answer it true, I'll start digging into the docs.

**Comment by Hiroshiba** [comment]
onnxランタイムへの移行はすでに計画中で、ある程度進んでいます。
うまく行っており、Nvidia製のGPUで動くことも一応確認済みです！
The migration to the onnx runtime is already in the planning stages and some progress has been made.
It's going well, and we've even confirmed that it works on Nvidia GPUs!

- https://github.com/Hiroshiba/voicevox_core/pull/21
- https://github.com/Hiroshiba/voicevox_core/tree/main/onnx

onnxランタイムへの移行でボトルネックになっているのは、onnxに関係ないこれらの機能実装です。
The bottleneck in the migration to onnx runtime is the implementation of these features that are not related to onnx.

- https://github.com/Hiroshiba/voicevox_core/issues/32
- https://github.com/Hiroshiba/voicevox_core/issues/31
- https://github.com/Hiroshiba/voicevox_core/issues/30
- https://github.com/Hiroshiba/voicevox_core/issues/29
- https://github.com/Hiroshiba/voicevox_core/issues/27

時間が取れたら実装したいと思っているのですが、なかなか取れずにペンディングっぽい状態になっています・・・。
もしご助力頂ければとても心強いです。
I'd like to implement it when I get the time, but I can't seem to get enough time and it's in a pending state...
If you can help me, I would be very grateful.

**Comment by Hiroshiba** [comment]
あ、すみません、質問の意図を把握し違えたかもしれません・・・。
Nvidia GPU以外のGPUに対応できないか、という質問でしょうか。
僕はonnxにあまり詳しくないので、どなたか詳しい方いらっしゃれば・・・！
---
Oh, sorry, I think I may have misunderstood the intent of your question...
The question is whether it is possible to support GPUs other than Nvidia GPUs.
I'm not very familiar with onnx, so if anyone knows anything about it...!

**Comment by Patchethium** [comment]
I see... Sorry I didn't make it clear :bowing_man: , I kind of wanted to ask the feasibility of supporting non-Nvidia GPUs with ORT, and also was wondering what it takes so long to get ORT done here.
I'll browse the issues to look what I can help, thanks!
