### ISSUE TITLE
ONNX版Raspberry Pi向けビルド（armhf）の追加

### ISSUE THREAD

**Issue by aoirint** [Hiroshiba/voicevox_core#40]
## 内容

ONNX版コアのRaspberry Pi向けビルドを追加するPRを出そうかと考えています。
検証を進めるうえで、とりあえずIssue化してみました。

OpenJTalkやAquesTalk Piの代替選択肢のような形でIoTシステム/ハードウェアに組み込む利用例を想定していますが、
それらと比べて音声合成に時間がかかるだろうという課題があります。

- OpenJTalkの利用例
    - [Raspberry Pi ロボットと会話する。 - Qiita](https://qiita.com/PonDad/items/05dba9e65533e8c98694)
    - [Open JTalkで初音ミクの声でおしゃべりさせる on Mac/Linux/Raspberry Pi - karaage. [からあげ]](https://karaage.hatenadiary.jp/entry/2016/07/22/073000)
    - [Raspberry piで日本語音声合成(Open JTalk)を試してみる。 - Qiita](https://qiita.com/lutecia16v/items/8d220885082e40ace252)
- AquesTalk Piの利用例
    - [Yahoo! Open Local Platform (YOLP) を使ってお天気情報を取得したついでにラズパイにAquesTalkPiで喋らせてみる - Qiita](https://qiita.com/tinaba/items/2fa13646c5ed73128ad0)
    - [Raspberry Pi でゆっくり達に Twitter タイムラインを読み上げてもらう - Qiita](https://qiita.com/mizo0203/items/7704e725a774bca4c2bc)
    - [研究室の Raspberry Pi (1才2ヶ月)に愛着が湧いている - Qiita](https://qiita.com/elzup/items/baab23ed37000cdb7384)

### Pros 良くなる点

- Raspberry Pi上でスタンドアロンで音声合成できるようになる
- IoTユーザを取り込めるかもしれない（利用の幅が広がる）

### Cons 悪くなる点

- Raspberry Pi上での音声合成には計算能力的に時間がかかるため、ユーザがネガティブな印象を受けるかもしれない
- 自動ビルドに時間がかかり、コアのリリース作業時間が伸びる
- ONNX Runtimeのビルドスクリプトの保守が必要になる

### 実現方法

- ONNX Runtimeのarmhf自動ビルドを作成する
- libcoreのarmhf自動ビルドを作成する

## OSの種類/ディストリ/バージョン

* Raspberry Pi / Raspberry Pi OS

**Comment by aoirint** [comment]
現在、ONNX Runtime v1.8.1とONNX版コアをarmhf用にGitHub Actions上でクロスコンパイルして、
Raspberry Pi 4B実機で[ONNX版のデモモデル](https://github.com/Hiroshiba/voicevox_core/tree/42b4df871e83913d8d505ec63e0dae79e6bed36b/onnx/model)を使って動作確認できています。

実験によると、音声合成にかかる時間は、
例文「これは本当に実行できているんですか」では、22.5秒程度でした。
並列化ライブラリのOpenMP（libgomp）ビルドオプションを有効化すると、16.5秒程度と少しですが音声合成が速くなりました。

ただ、libgompへの依存が増えることと、理由はよくわかりませんがONNX Runtimeの公式ビルドでは、v1.7.0からOpenMPが無効化されているという点が気になっています。

- ONNX Runtime v1.7.0のリリースノート
    - > Starting from this release, all ONNX Runtime CPU packages are now built without OpenMP.
    - https://github.com/microsoft/onnxruntime/releases/tag/v1.7.0
- ONNX Runtimeを組み込むにあたって依存を減らしたい意図がある?（`noncontribops`がなにかわからないけれど）
    - > The nocontribops pipeline is used by the Edge browser team and (going forward) the vscode team. Both these teams don't want their users to install any external dependency to use ORT.
    - <https://github.com/microsoft/onnxruntime/pull/2888>
- CI上でOpenMPフラグの無効化
    - <https://github.com/microsoft/onnxruntime/pull/6609>

**Comment by aoirint** [comment]
検証のログです。

## OpenMP有効化

- <https://github.com/aoirint/voicevox_core/releases/tag/0.8.0-aoirint-7>

```shell
sudo apt install libgomp1
```

<details>

```shell
$ time python3 ../../example/python/run.py --text "これは本当に実行できているんですか" --speaker_id 1
real	0m16.295s
user	0m45.777s
sys	0m6.019s

$ time python3 ../../example/python/run.py --text "これは本当に実行できているんですか" --speaker_id 1
real	0m16.354s
user	0m46.850s
sys	0m5.620s

$ time python3 ../../example/python/run.py --text "これは本当に実行できているんですか" --speaker_id 1
real	0m16.313s
user	0m46.620s
sys	0m5.645s
```

</details>

### OMP_NUM_THREADS
[ONNX Runtime v1.6.0のリリースノート](https://github.com/microsoft/onnxruntime/releases/tag/v1.6.0)のAdditional notesに、OpenMPの機能として実行時の環境変数`OMP_NUM_THREADS`でパフォーマンス調整ができるとあったので試してみました。
デフォルトで実行環境のCPUコア数（一番いい値）が使われていそうなので、調整の必要はなさそうでした。

<details>

```shell
# 指定なし
$ time python3 ../../example/python/run.py --text "これは本当に実行できているんですか" --speaker_id 1
real	0m16.546s
user	0m46.318s
sys	0m5.812s

$ time OMP_NUM_THREADS=0 python3 ../../example/python/run.py --text "これは本当に実行できているんですか" --speaker_id 1
libgomp: Invalid value for environment variable OMP_NUM_THREADS

real	0m16.443s
user	0m46.383s
sys	0m5.812s

$ time OMP_NUM_THREADS=2 python3 ../../example/python/run.py --text "これは本当に実行できているんですか" --speaker_id 1

real	0m22.893s
user	0m37.147s
sys	0m4.616s

$ time OMP_NUM_THREADS=8 python3 ../../example/python/run.py --text "これは本当に実行できているんですか" --speaker_id 1

real	0m17.143s
user	0m44.683s
sys	0m6.012s

```

</details>

## OpenMP無効化

- <https://github.com/aoirint/voicevox_core/releases/tag/0.8.0-aoirint-6>

<details>

```shell
$ time python3 ../../example/python/run.py --text "これは本当に実行できているんですか" --speaker_id 1
real	0m22.479s
user	0m36.972s
sys	0m5.548s

$ time python3 ../../example/python/run.py --text "これは本当に実行できているんですか" --speaker_id 1
real	0m22.361s
user	0m37.260s
sys	0m5.160s

$ time python3 ../../example/python/run.py --text "これは本当に実行できているんですか" --speaker_id 1
real	0m22.530s
user	0m37.409s
sys	0m5.029s
```

</details>

## テスト環境

- Raspberry Pi 4 Model B Rev 1.2
- Raspberry Pi OS Buster
- 推論コード・モデル: <https://github.com/Hiroshiba/voicevox_core/commit/42b4df871e83913d8d505ec63e0dae79e6bed36b>
- ONNX Runtime v1.8.2（GitHub Actions上で自前クロスコンパイル）
    - https://github.com/aoirint/voicevox_core/blob/0.8.0-aoirint-7/.github/workflows/build.yml
    - https://github.com/aoirint/voicevox_core/blob/0.8.0-aoirint-6/.github/workflows/build.yml
    - Compare: https://github.com/aoirint/voicevox_core/compare/0.8.0-aoirint-6...0.8.0-aoirint-7

<details>

```shell
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10
Codename:	buster

$ cat /proc/cpuinfo 
processor	: 0
model name	: ARMv7 Processor rev 3 (v7l)
BogoMIPS	: 126.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

processor	: 1
model name	: ARMv7 Processor rev 3 (v7l)
BogoMIPS	: 126.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

processor	: 2
model name	: ARMv7 Processor rev 3 (v7l)
BogoMIPS	: 126.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

processor	: 3
model name	: ARMv7 Processor rev 3 (v7l)
BogoMIPS	: 126.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

Hardware	: BCM2711
Revision	: c03112
Serial		: 10000000a52512b4
Model		: Raspberry Pi 4 Model B Rev 1.2

$ python3 -V
Python 3.7.3

$ pip3 show numpy
Name: numpy
Version: 1.21.3
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: BSD
Location: /home/pi/.local/lib/python3.7/site-packages
Requires: 
Required-by: microdotphat, pyopenjtalk, scrollphathd, sense-ha
```

</details>

**Comment by aoirint** [comment]
ONNX Runtime v1.9.0以降のビルドにはまだ成功していないです。

ONNX Runtimeが依存するpytorch_cpuinfoが、cpuid.hをincludeしようとして失敗しています。

- <https://github.com/aoirint/voicevox_core/runs/4204427752>

```
In file included from /home/runner/work/voicevox_core/voicevox_core/cmake/external/pytorch_cpuinfo/src/x86/init.c:5:
/home/runner/work/voicevox_core/voicevox_core/cmake/external/pytorch_cpuinfo/src/x86/cpuid.h:5:11: fatal error: cpuid.h: No such file or directory
  #include <cpuid.h>
           ^~~~~~~~~
compilation terminated.
```

**Comment by HyodaKazuaki** [comment]
IoT用途であればRaspberry Pi単体で利用することは想定しなくても良いと思います。
Issue本体に書かれているように、Raspberry Pi単体の性能は限られていて推論に不向きです。
そのため、Coral USB AcceleratorやNeural Compute Stick 2などの推論に特化したデバイスを接続し、その上で利用することが現実的だと思います。

**Comment by Hiroshiba** [comment]
面白そうだなと思います！
たしかに @HyodaKazuaki さんの仰るとおり、ラズパイ上で直接動かす機会は小さいかもですが、将来ライト版などが出て軽くなったら面白いかもです。

論点がいくつかありそうで、１つずつ挙げてみます。

### ラズパイ向けのonnxの自前ビルドをメンテしていくか

onnxのビルドをしなくても、今提供しているVOICEVOXは問題なく作成できるので、新たに風呂敷を広げなくても良いという考え方もありそうです。
これに関しては、将来的にスマホ向け版のビルドとかも視野に入れたいのでお手本代わりに便利そうなので、とりあえずマージしても良いのかなと思いました。

難しくなったらメンテをやめるか考える、くらいの心意気です。

### このリポジトリで管理すべきか

コアから必要なのはonnxビルド済みのライブラリなのと、onnx自体は本体（コア）に完全に非依存でビルド可能なので、本当ならリポジトリを分けたほうが良いなと思います。
が、分けるかどうか考えるのはVOICEVOX orgが出来てからで良いと思います。

### ビルドが遅くなるのをどうするか

ただ、ビルドが数時間単位で遅くなってしまうのは流石に課題かなと思いました。
これはビルド済みの成果物をキャッシュできれば良いかなと思います。
artifactにキャッシュしておいて、キャッシュがなければビルドする感じです。

現在のgithub actionsでこれ（キャッシュがなければビルドする）をやろうとすると、いたる所に if cache が必要で大変そうなので、ちょっと工夫したいところです。

**Comment by aoirint** [comment]
> ONNX Runtime v1.9.0以降のビルド

いろいろ試してみてビルドできました。

CMakeの設定で、
`CMAKE_SYSTEM_PROCESSOR=armv7l`という指定をする必要があるのはリリースノートからわかっていたのですが、
`CMAKE_SYSTEM_NAME=Linux`という指定を合わせて明示的に与えてあげる必要があるみたいでした。

**Comment by aoirint** [comment]
@Hiroshiba 

> 難しくなったらメンテをやめるか考える、くらい

> 分けるかどうか考えるのはVOICEVOX orgが出来てからで良い

いいと思います。

> ビルド済みの成果物をキャッシュ

#41 の方で実装済みです。デフォルトブランチで一度ビルドされれば、キャッシュを利用できるので、ビルド時間に大きく影響しないと思います。
